version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      minor-patch:
        update-types:
          - "minor"
          - "patch"
        exclude-patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
      react-ecosystem:
        patterns:
          - "react"
          - "react-dom"
          - "@types/react"
          - "@types/react-dom"
        update-types:
          - "patch"
          - "minor"
          - "major"
